### ISSUE TITLE
Crackling, then sound stops. Probably doing it all wrong...

### ISSUE THREAD

**Issue by everythingability** [Tonejs/Tone.js#510] opened 2019-07-09 10:05 UTC
Hello...

I'm trying to make a Brian Eno-like experience based on proximity to a database of trees.

http://projects.everythingability.com/local/musicofthetrees/

My example shows random trees, and a "radar" plays each tree... But after a while, they start to crackle, and after a few minutes, the audio stops entirely.

I am probably doing it all wrong. Each tree has a species, height and width, I wanted the sound of each tree to be different, changing the effects, or duration based on distance from the centre and its size etc.

The number of trees will be always changing, as will their distance from the centre.

I tried creating ONE SYNTH global and storing it in each Tree object... then adding envelopes and effects... and I tried creating a SYNTH FOR EACH TREE, each time a sweep of the radar does a Tree.check() ... and the results are the same. It works for a while (with crackles) then eventually bombs out.

I've tried lots of the suggestions from this forum, but none seem to help and I think I've got it fundamentally wrong somehow.

Conceptually, which is the *best* way of working, given they aren't like keys on a keyboard, because their parameters will keep changing all the time as I walk through the trees? Ideally I'd like each tree to have a riff... but I can't get them to plinky plonk nicely yet.

Thanks for any suggestions.

Tom

**Comment by tambien** [comment] 2019-07-09 17:24
Sounds like a cool project! doesn't seem to be running currently, but that makes sense if it's under active development. in general you want to limit the number of nodes that you create and adding more over time without disposing/disconnecting old ones can cause the browser to run out of memory and eventually give up on rendering audio, which might what you're experiencing. All of the components have a 'dispose' method which will disconnect the web audio nodes to signal to the Garbage Collection that the node can be freed from memory. 

i think there are multiple approaches that might work for what you're describing: you could either create a new synth and effects chain for each tree and after it plays its riff, dispose of each of the objects associated with that tree. Or alternatively create a static number of audio objects (while staying under the limit of the number that causes your system to overload) and then trade off which tree is controlling that synth chain. 

i'm going to close this issue for now since it's a little too general currently to be actionable. If you do find a way to distill/reproduce this issue without too many other dependencies, that'd be helpful in identifying what if anything that could be fixed on the Tone.js-side.

**Closed by tambien** 2019-07-09 17:24 UTC
