### ISSUE TITLE
Need sample of non-sampler instruments

### ISSUE THREAD

**Issue by sarahBuisson** [Tonejs/Tone.js#724] opened 2020-08-27 08:09 UTC
Hello, 
Your lib is very powerfull, specialy for the pure Synth part, but consequently very hard to use when you have a precise idea in mind.

You should add example code of instrument config by reference of how it sound, in complement of the sample instrument you already show.

I mean thing like : 
this instrument sound like an e-piano , an  e-viole, ... 

Currently your sample are just like : this instrument is an exemple of what you can do with the AMSynth class.

Because instrument using sampler synth are very intuitive to configure,  I also think those added examples shouldn't be SamplerSynth implementation.

**Comment by TaoJinjin-Thomas** [comment] 2020-08-27 16:02
What is 'SamplerSynth'?
If you mean you want to know those Synth works, you can check out the API doc: https://tonejs.github.io/docs/13.8.25/Synth
it has pretty detailed instructions. If you mean why the sound sounds like that, then I guess you probably need to know some DSP or audio processing knowledge.

**Comment by sarahBuisson** [comment] 2020-08-27 16:23
by SamplerSynth  , I mean : https://tonejs.github.io/docs/14.7.39/Sampler.html

**Comment by sarahBuisson** [comment] 2020-08-27 16:34
> it has pretty detailed instructions. If you mean why the sound sounds like that, then I guess you probably need to know some DSP or audio processing knowledge.

I "understand" how those synth works, the same way I understand how a pencil work. But understanding a pencil will not allow me to draw a masterpiece without knowledge about painting. But I can alway copie some existing drawing and adapt it to my need.

Same way for the synth. A few exemple of various instrument would help. 
I understand the base of enveloppe and ADSR , but don't have experience. I'm not able to make an instrument sound the way I want it to, but I'm able to adapt an instrument with a near sonority to my need. I just need an example of code to adapt.

I suppose there is also other people who would like to use toneJs using an already existing instrument with a sonority near some "acoustique" instrument they already know.

**Comment by tambien** [comment] 2020-08-27 19:10
I like that analogy about the pencil and agree that what you're describing would be an amazing resource. I think currently Tone.js is more of a pencil than a guide on illustration. Personally, i'm not an expert in instrument modeling and most of the synths might be a little too simple to convincingly mimic many instruments, so i often rely on Sampler if i'm trying to reproduce the sound of an instrument. 

If other people have resources on instrument modeling in Tone.js and/or Web Audio, i would love to link to it. I know of these guides: [synth secrets](https://www.soundonsound.com/series/synth-secrets) for general advice on synthesis and modeling. [learning synths](https://learningsynths.ableton.com/) is also a great sound-design resource. 

This issue might be a duplicate of #677

**Closed by tambien** 2020-08-27 19:10 UTC
