### ISSUE TITLE
Chome, Players not calling onload callback

### ISSUE THREAD

**Issue by LukaszGrela** [Tonejs/Tone.js#772] opened 2020-10-28 16:28 UTC
I have this simple app that I've made: js30.greladesign.co/01 which works fine when run from a remote location, I've noticed however that when developed on  windows machine I cant get the app to work. It seems like the `onload` callback of the `Players` is not called even though the files are loaded (Network tab shows them loaded). I haven't noticed this until today as I was dev'ing this on my linux laptop and it was working there. Do you have any idea what's going on?

 * Tone.js v14.7.58 * 
Chrome 86.0.4240.111

**Comment by tambien** [comment] 2020-10-29 14:51
Could you provide a minimal example with source code? 

My guess is this might have to do with race conditions and the buffer is already loaded by the time it's passed into Tone.Players. How are you loading the buffers?

**Comment by LukaszGrela** [comment] 2020-10-30 08:57
I'm using React, I have prepared the `Instruments` class to encapsulate the initiation and accessing the instrument:

```
class Instruments {
  instruments = [
    { key: "A", keyCode: 65, label: "clap" },
    { key: "S", keyCode: 83, label: "hihat" },
    { key: "D", keyCode: 68, label: "kick" },
    { key: "F", keyCode: 70, label: "openhat" },
    { key: "G", keyCode: 71, label: "boom" },
    { key: "H", keyCode: 72, label: "ride" },
    { key: "J", keyCode: 74, label: "snare" },
    { key: "K", keyCode: 75, label: "tom" },
    { key: "L", keyCode: 76, label: "tink" },
  ];
  players: Players | undefined = undefined;

  load(callback?: () => void): void {
    this.players = new Players(
      this.instruments.reduce((acc, instrument) => {
        return {
          ...acc,
          [instrument.key]: `./sound/${instrument.label}.mp3`,
        };
      }, {}),
      (): void => {
        this.players?.toDestination();
        callback && callback();
      }
    );
  }

  play(instrument: string): void {
    const found = this.instruments.find(
      (needle): boolean => `${needle.keyCode}` === instrument
    );
    if (found) {
      if (this.players?.has(found.key)) {
        this.players?.player(found.key).start();
      }
    }
  }
}
```
then when user selects "tap to start" I'm calling

```
            <button
              className="tap-to-start"
              onClick={async () => {
                await Tone.start();
                Tone.context.resume();
                instruments.load(() => {
                   console.log("I'm loaded");
                })
              }}
            >
              Tap to start
            </button>
```
// The "I'm loaded" is never displayed when on windows chrome, the console shows however (and network tab) that files are loaded though `Fetch finished loading: GET "<URL>".`

also having following in the console log (which I thought was resolved with  `await Tone.start(); Tone.context.resume())`:

```
 * Tone.js v14.7.58 * 
audio-context-constructor.ts:40 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
AudioContext @ audio-context-constructor.ts:40
createAudioContext @ AudioContext.ts:13
Context @ Context.ts:124
getContext @ Global.ts:26
./node_modules/tone/build/esm/index.js @ index.ts:33
__webpack_require__ @ bootstrap:784
fn @ bootstrap:150
./src/App.tsx @ App.css?4433:45
__webpack_require__ @ bootstrap:784
fn @ bootstrap:150
./src/index.tsx @ index.css?f3f6:45
__webpack_require__ @ bootstrap:784
fn @ bootstrap:150
1 @ serviceWorker.ts:149
__webpack_require__ @ bootstrap:784
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
test-audio-node-disconnect-method-support.ts:45 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous) @ test-audio-node-disconnect-method-support.ts:45
testAudioNodeDisconnectMethodSupport @ test-audio-node-disconnect-method-support.ts:4
(anonymous) @ audio-node-constructor.ts:290
(anonymous) @ cache-test-result.ts:18
AudioNode @ audio-node-constructor.ts:286
AudioDestinationNode @ audio-destination-node-constructor.ts:33
MinimalBaseAudioContext @ minimal-base-audio-context-constructor.ts:29
BaseAudioContext @ base-audio-context-constructor.ts:51
AudioContext @ audio-context-constructor.ts:59
createAudioContext @ AudioContext.ts:13
Context @ Context.ts:124
getContext @ Global.ts:26
./node_modules/tone/build/esm/index.js @ index.ts:33
__webpack_require__ @ bootstrap:784
fn @ bootstrap:150
./src/App.tsx @ App.css?4433:45
__webpack_require__ @ bootstrap:784
fn @ bootstrap:150
./src/index.tsx @ index.css?f3f6:45
__webpack_require__ @ bootstrap:784
fn @ bootstrap:150
1 @ serviceWorker.ts:149
__webpack_require__ @ bootstrap:784
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
test-audio-scheduled-source-node-start-method-negative-parameters-support.ts:7 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
testAudioScheduledSourceNodeStartMethodNegativeParametersSupport @ test-audio-scheduled-source-node-start-method-negative-parameters-support.ts:7
(anonymous) @ native-constant-source-node-factory.ts:27
(anonymous) @ cache-test-result.ts:18
(anonymous) @ native-constant-source-node-factory.ts:27
ConstantSourceNode @ constant-source-node-constructor.ts:42
createConstantSource @ base-audio-context-constructor.ts:92
createConstantSource @ Context.ts:188
ToneConstantSource @ ToneConstantSource.ts:27
Signal @ Signal.ts:67
TickSignal @ TickSignal.ts:38
TickSource @ TickSource.ts:53
Clock @ Clock.ts:84
Transport @ Transport.ts:172
(anonymous) @ Transport.ts:724
(anonymous) @ ContextInitialization.ts:24
initializeContext @ ContextInitialization.ts:24
initialize @ Context.ts:156
get transport @ Context.ts:271
./node_modules/tone/build/esm/index.js @ index.ts:33
__webpack_require__ @ bootstrap:784
fn @ bootstrap:150
./src/App.tsx @ App.css?4433:45
__webpack_require__ @ bootstrap:784
fn @ bootstrap:150
./src/index.tsx @ index.css?f3f6:45
__webpack_require__ @ bootstrap:784
fn @ bootstrap:150
1 @ serviceWorker.ts:149
__webpack_require__ @ bootstrap:784
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
Show 2 more frames
constant-source-node-constructor.ts:85 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
start @ constant-source-node-constructor.ts:85
start @ ToneConstantSource.ts:73
Signal @ Signal.ts:75
TickSignal @ TickSignal.ts:38
TickSource @ TickSource.ts:53
Clock @ Clock.ts:84
Transport @ Transport.ts:172
(anonymous) @ Transport.ts:724
(anonymous) @ ContextInitialization.ts:24
initializeContext @ ContextInitialization.ts:24
initialize @ Context.ts:156
get transport @ Context.ts:271
./node_modules/tone/build/esm/index.js @ index.ts:33
__webpack_require__ @ bootstrap:784
fn @ bootstrap:150
./src/App.tsx @ App.css?4433:45
__webpack_require__ @ bootstrap:784
fn @ bootstrap:150
./src/index.tsx @ index.css?f3f6:45
__webpack_require__ @ bootstrap:784
fn @ bootstrap:150
1 @ serviceWorker.ts:149
__webpack_require__ @ bootstrap:784
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
```

**Comment by tambien** [comment] 2020-10-30 15:27
unfortunately i don't have any way to debug this if it's windows+chrome specific. It works totally fine for me on mac and linux. 

Does `Tone.loaded()` resolve? And also is `this.players.loaded === true`?

**Comment by LukaszGrela** [comment] 2020-11-02 09:33
```
Tone.loaded - resolved
Fetch finished loading: GET "<URL>". <- console Log XMLHttpRequests
players.loaded false
```
so the `Tone.loaded` resolves but the `Players` `loaded` property returns `false`, the console option to `Log XMLHttpRequests` shows the fetches (as well as I can see them in the network tab), so it started loading but I guess it can't get the finished event.

**Comment by tambien** [comment] 2020-11-04 19:26
is it possible that the audio file is not being decoded correctly and somehow failing silently? Are you able to set a breakpoint at [this function](https://github.com/Tonejs/Tone.js/blob/14be0fc84ebb9512ac1a6d7dcaf3e2d1f2133e39/Tone/core/context/ToneAudioBuffer.ts#L380) to see if everything is able to decode the audio file that you're giving it?

**Comment by tambien** [comment] 2021-01-13 18:06
I'm going to close this since i'm able to reproduce this issue and therefor unable to debug it meaningfully. 

Please comment if you're still experiencing the issue with a test case and i'll reopen.

**Closed by tambien** 2021-01-13 18:06 UTC
Labels: can't reproduce
