### ISSUE TITLE
Setting the current transport time

### ISSUE THREAD

**Issue by alexthewilde** [Tonejs/Tone.js#182] opened 2016-11-24 17:58 UTC
I need to directly set the current Transport time. According to the docs, this can be achieved with `Tone.Transport.seconds = 30`.

This indeed alters the value temporarily, but it'll get reset to 0 afterwards internally. This can be verified with `setTimeout(function(){ console.log(Tone.Transport.seconds) }, 1)`.

The only way I've found to make it work is this using this workaround:
```
Tone.Transport.seconds = 30;
Tone.Transport.start(undefined, Tone.Transport.position);
Tone.Transport.pause();
```

I'm wondering if there's another, less hackish way?

**Comment by tambien** [comment] 2016-11-24 18:33
Trying to reproduce the issue [here](https://jsfiddle.net/mzt1e1wn/3/), but was unable to. Does this work for you?

**Comment by alexthewilde** [comment] 2016-11-25 12:56
Yes your example works, but the difference is that you're testing against an actively running transport.

I was actually referring to setting the current time on an inactive transport. See the modified [example](https://jsfiddle.net/tv78f7wL/) where `Tone.Transport.seconds` snaps back to 0.

**Comment by tambien** [comment] 2016-12-06 02:49
Thanks for the clarification and updated jsfiddle. That is a strange bug that reading the value changes it. 

I'm not sure exactly which commit it was, but it seems to be already fixed in the latest build of Tone.js. [Here's](https://jsfiddle.net/tv78f7wL/1/) your fiddle with the latest build from the dev branch pasted in. Correctly prints 30 the entire time.

**Comment by alexthewilde** [comment] 2016-12-16 08:54
@tambien confirmed that it works with latest dev, thanks for taking the time to test this!

Any idea when the next release is going to be available?

**Comment by tambien** [comment] 2016-12-16 19:34
pretty soon! just a couple small things I want to do before i push a release.

**Closed** 2017-01-08 23:36 UTC
