### ISSUE TITLE
PolySynth(DuoSynth) issues

### ISSUE THREAD

**Issue by CptCaveira** [Tonejs/Tone.js#818] opened 2021-01-08 12:57 UTC
Hi,

I've come upon some issues using the DuoSynth inside the the PolySynth, i´ve tried to look this up in the forum and through older issues but I haven't quite found a solution. 
Since I am, admittedly, a beginner this might be a case of incompetence rather than actual problems but here it goes:

 - using the keyboard to play the polysynth, some notes will become stuck, I think this has something to do with the fact that when a key is pressed it repeats the value and tried to address it,  but it is still happening usually when the note count is high (but still not exceding maxPolyphony).
 
 - I am also unable to set the frequency value for the filter for voice0 and voice1, this seems to be the only value I can't access with the set() method.
 
The code is a bit of a mess, but here it is:

https://jsfiddle.net/9075fpbq/

**Comment by tambien** [comment] 2021-01-08 15:11
hi @CptCaveira 

> using the keyboard to play the polysynth, some notes will become stuck, I think this has something to do with the fact that when a key is pressed it repeats the value and tried to address it, but it is still happening usually when the note count is high (but still not exceding maxPolyphony).

Unfortunately, I'm unable to recreate this. I just played around for 5 minutes smashing the keys on my keyboard, but couldn't get a note to stay stuck. 

> I am also unable to set the frequency value for the filter for voice0 and voice1, this seems to be the only value I can't access with the set() method.

This is actually by design. The filter frequency is controlled by the `filterEnvelope` which means that it's value is dynamic and can't be set explicitly. You should be able to adjust how the filterEnvelope controls the frequency using the `baseFrequency` and `octaves` properties.

**Comment by CptCaveira** [comment] 2021-01-08 17:41
Thanks for the reply!
The frequency thing is a weight off my mind, I was really going nuts with it.

As for the sticking, here is an example of what i mean:

https://user-images.githubusercontent.com/71012028/104046490-786f0d00-51e0-11eb-8cee-de4724c8fb3e.mp4

starting at around the 12s mark is my issue.
If you can think of a way that I can give you some more information on it please let me know.

**Comment by tambien** [comment] 2021-01-11 17:06
I have a feeling this is likely because internally everything in Tone.js is scheduled with a small lookAhead and that somehow the release is being triggered before the attack is invoked. Not quite sure why this would be unless the events somehow came out of order. 

As i said i'm unable to reproduce this behavior, but see if something like this might bandaid things:

```js

poly.triggerAttack(notes[QWERTZ.indexOf(event.key)], Tone.immediate());

...
poly.triggerRelease(notes[QWERTZ.indexOf(event.key)], Tone.immediate());

```

**Comment by CptCaveira** [comment] 2021-01-11 20:44
Hey, 
so I tried it out and some notes will still get stuck, and play continuously like previously, but now if the same key is hit again the release is triggered and the page doesn't need to be reloaded. It helps out a lot!

Thanks for your time!

**Comment by tambien** [comment] 2021-01-13 17:38
If it's working for you now, i'm going to close this issue. 

If you're still having this issue, and you're able to create a with a test case which can be produced without mashing the keys (since there's a lot of variability there), that'd be really helpful in debugging where the issue is and we can reopen it.

**Closed by tambien** 2021-01-13 17:38 UTC
