### ISSUE TITLE
Player: quickly starting and stopping. Problems with Source._stateAtTime()

### ISSUE THREAD

**Issue by lukephills** [Tonejs/Tone.js#74] opened 2015-07-04 11:35 UTC
Hi Yotam,

I've noticed a bug in the Player. If you immediately switch between `start()` and `stop()` quickly, the sound doesn't start as expected. The easiest way to notice this is if you use a keyboard.

As a test I replaced the current start and stop methods in source.js with older methods that don't use `_stateAtTime()` and it worked so I think there is an error in the current functionality but I can't work it out.

```
Tone.Source.prototype._stateAtTime = function(time){
		time = this.toSeconds(time);
		if (this._nextStart <= time && this._nextStop > time){
			return Tone.Source.State.STARTED;
		} else if (this._nextStop <= time){
			return Tone.Source.State.STOPPED; // Do we need this else if?
		} else {
			return Tone.Source.State.STOPPED;  
		}
	};
```

**Comment by lukephills** [comment] 2015-07-04 12:14
To add this only happens with a Player. No problems with the Noise or Oscillator

**Comment by tambien** [comment] 2015-12-12 16:56
I'm going to close this for now since it has to do with the old implementation. Please reopen if the issue is still there.

**Closed by tambien** 2015-12-12 16:56 UTC
