### ISSUE TITLE
Player cannot stop playing or scheduled sounds

### ISSUE THREAD

**Issue by jtgrassie** [Tonejs/Tone.js#266] opened 2017-10-10 20:37 UTC
Having scheduled players to start in the future, they subsequently cannot be stopped. The only way to stop them is to `disconnect()`. The problem then is that calling `start()` (after reconnecting to master), the player is very glitchy.

**Comment by tambien** [comment] 2017-10-11 19:35
can you link an example with jsfiddle or something so that i can validate any patches?

**Comment by tambien** [comment] 2017-10-21 17:50
I believe this is a duplicate of #258

**Closed** 2017-11-29 21:30 UTC
