### ISSUE TITLE
macos Safari:TypeError: undefined is not an object (evaluating 'nativeAudioScheduledSourceNode.connect(nativeGainNode)')

### ISSUE THREAD

**Issue by TaoJinjin-Thomas** [Tonejs/Tone.js#714] opened 2020-08-17 10:20 UTC
<img width="722" alt="Screen Shot 2020-08-17 at 6 16 13 PM" src="https://user-images.githubusercontent.com/17539265/90385465-c6f70000-e0b5-11ea-8661-c4582a35f807.png">

I am using 14.7.39 typescript  Tonejs.
the code runs with no problem in chrome and firefox, but safari will throw this error.

**Comment by TaoJinjin-Thomas** [comment] 2020-08-17 10:48
Ok, I saw a previous bug report that talks about the same problem. It looks like relates to my safari's version.

**Comment by tambien** [comment] 2020-08-17 20:50
ok moving the discussion to there then. duplicate of #695

**Closed by tambien** 2020-08-17 20:50 UTC
