### ISSUE TITLE
FireFox - SyntaxError: An invalid or illegal string was specified

### ISSUE THREAD

**Issue by acgillette** [Tonejs/Tone.js#245] opened 2017-07-24 20:33 UTC
I am using a tone.js script in a project I'm building. It works fine in Chrome and Safari, but when I attempt to play it in Firefox I get this error. 

Here is the full trace: 
```
Tone.TimelineSignal.prototype.exponentialRampToValueAtTime https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:3715:14
	Tone.Param.prototype.exponentialRampToValue https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:2943:10
	Tone.Envelope.prototype.triggerAttack https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:4301:10
	Tone.DuoSynth.prototype._triggerEnvelopeAttack https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:19364:10
	Tone.Monophonic.prototype.triggerAttack https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:18698:10
	Tone.Instrument.prototype.triggerAttackRelease https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:18630:10
	<anonymous> http://0.0.0.0:8080/bundle.js:19974:7
	Tone.Loop.prototype._tick https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:16188:10
	bound  self-hosted:915:17
	Tone.Event.prototype._tick https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:15978:14
	bound  self-hosted:913:17
	Tone.Transport.prototype._processTick/< https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:8209:18
	Tone.IntervalTimeline.prototype.forEachAtTime https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:7751:22
	Tone.Transport.prototype._processTick https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:8207:10
	bound  self-hosted:913:17
	Tone.Clock.prototype._loop https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:7405:22
	bound  self-hosted:911:17
	Tone.Emitter.prototype.emit https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:2158:22
	Tone.Context.prototype._createWorker/< https://cdnjs.cloudflare.com/ajax/libs/tone/0.10.0/Tone.js:2306:14
	bound 
```

And here is the script I'm using: 

```
var $ = require('jquery');
var musicOn = true;

const EQUALIZER_CENTER_FREQUENCIES = [
  100, 125, 160, 200, 250, 315, 400, 500, 630, 800, 1000, 1250, 1600,
  2000, 2500, 3150, 4000, 5000, 6300, 8000, 10000
];

function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min)) + min;
}


function makeSynth() {

let envelope = {
    attack: 0.1,
    release: 4,
    releaseCurve: 'linear'
  };

let filterEnvelope = {
  baseFrequency: 200,
  octaves: 2,
  attack: 0,
  decay: 0,
  release: 1000
};

return new Tone.DuoSynth({
  harmonicity: 1,
  volume: -20,
  voice0: {
    oscillator: {type: 'sawtooth'},
    envelope,
    filterEnvelope

},
voice1: {
  oscillator: { type: 'sine'},
  envelope,
  filterEnvelope
},
vibratoRate: 0.5,
vibratoAmount: 0.1
});
}

$(document).ready(function() {
  var musicToggle = window.location.search ? window.location.search.split('?')[1].split("=")[1] : "true";

  $(".a-enter-vr-button").click(function() {


  let leftSynth = makeSynth();
  let rightSynth = makeSynth();

  let leftPanner = new Tone.Panner(-0.5).toMaster();
  let rightPanner = new Tone.Panner(0.5).toMaster();
  let equalizer = EQUALIZER_CENTER_FREQUENCIES.map(frequency => {
    let filter = Tone.context.createBiquadFilter();
    filter.type = 'peaking';
    filter.frequency.value = frequency;
    filter.Q.value = 4.31;
    filter.gain.value = getRandomInt(-13, 12);
    return filter;
  });
  let echo = new Tone.FeedbackDelay('16n', 0.2);
  let delay = Tone.context.createDelay(6.0);
  let delayFade = Tone.context.createGain();

  delay.delayTime.value = 6.0;
  delayFade.gain.value = 0.75;

  leftSynth.connect(leftPanner);
  rightSynth.connect(rightPanner);
  leftPanner.connect(equalizer[0]);
  rightPanner.connect(equalizer[0]);
  equalizer.forEach((equalizerBand, index) => {
    if(index < equalizer.length - 1) {
      equalizerBand.connect(equalizer[index + 1]);
    } else {
      equalizerBand.connect(echo);
    }
  });
  leftPanner.connect(echo);
  rightPanner.connect(echo);
  echo.toMaster();
  echo.connect(delay);
  delay.connect(Tone.context.destination);
  delay.connect(delayFade);
  delayFade.connect(delay);

  new Tone.Loop(time => {
    leftSynth.volume.value = -40;

    leftSynth.triggerAttackRelease('C5', '1:2', time)

    leftSynth.setNote('D5', '+0:2');

    leftSynth.triggerAttackRelease('E4', '0:2', '+6.0');

    leftSynth.triggerAttackRelease('G4', '0:2', '+11:2');

    leftSynth.triggerAttackRelease('E5', '2:0', '+19:0');
    leftSynth.setNote('G5', '+19:1:2', 0.5);
    leftSynth.setNote('A5', '+19:3:0', 0.5);
    leftSynth.setNote('G5', '+19:4:2', 0.5);
    }, '34m').start();



  new Tone.Loop(time => {
    rightSynth.volume.value = -40;


    rightSynth.triggerAttackRelease('D4', '1:2', '+5:0');

    rightSynth.setNote('E4', '+6.0');

    rightSynth.triggerAttackRelease('B3', '1m', '+11:2:2');

    rightSynth.setNote('G3', '+12:0:2');

    rightSynth.triggerAttackRelease('G4', '0.2', '+23.2');

  }, '37m').start();

  if(musicToggle === "true") {
    Tone.Transport.start();
  }

  });
});
```
I'm unsure if this is a firefox issue or an issue with my script.

**Comment by tambien** [comment] 2017-07-25 19:55
Thanks for the issue. i think this is related to #239. The error is not thrown if you schedule the time slightly in the future like [this](https://jsfiddle.net/q8qz9b4y/).

I've fixed this problem in the latest dev build. You can checkout the results [here](https://jsfiddle.net/9Lb9j0hg/). 

I'm going to close for now, since it seems to be a duplicate of #239 and it's easier for me to track it in one place.

**Closed by tambien** 2017-07-25 19:55 UTC
