### ISSUE TITLE
Disposing objects throws error when using via NPM

### ISSUE THREAD

**Issue by schtibe** [Tonejs/Tone.js#259] opened 2017-09-08 15:01 UTC
I installed ToneJS via NPM. When calling `.dispose()` on an instrument, it throws an error:

```
504:67 Uncaught TypeError: Cannot read property 'dispose' of undefined
    at Tone.Gain.dispose (504:67)
    at Tone.Volume.dispose (543:88)
    at Tone.PolySynth.Tone.Instrument.dispose (607:89)
    at Tone.PolySynth.dispose (609:242)
    at eval (557:487)
```

My tone setup is like this:
```
import Freeverb from 'tone/Tone/effect/Freeverb'
import Vibrato from 'tone/Tone/effect/Vibrato'
import Synth from 'tone/Tone/instrument/Synth'
import PolySynth from 'tone/Tone/instrument/PolySynth'
import EQ3 from 'tone/Tone/component/EQ3'
import Distortion from 'tone/Tone/effect/Distortion'

export default class Synthie {
  constructor () {
    this.createPianoSynthie()
    this.createFailSynthie()
  }

  createPianoSynthie () {
    const synthSettings = {
      oscillator: {
        type: 'sine',
        volume: -21
      },
      envelope: {
        attack: 0.005,
        decay: 1.2,
        sustain: 0.05,
        release: 0.6
      }
    }

    const reverbSettings = {
      roomSize: 0.05,
      wet: 0.2
    }

    const reverb = new Freeverb(reverbSettings).toMaster()

    const vibrato = new Vibrato({
      frequency: 2.5
    }).connect(reverb)

    const equalizer = new EQ3(2, 5, 10).connect(vibrato)

    this.piano = new PolySynth(5, Synth, synthSettings).connect(equalizer)
  }

  createFailSynthie () {
    const synthSettings = {
      oscillator: {
        type: 'square',
        volume: -20
      },
      envelope: {
        attack: 0.001,
        decay: 0.6,
        sustain: 0.005,
        release: 0.1
      }
    }

    const equalizer = new EQ3(2, 0, 0).toMaster()

    const distorter = new Distortion(0.8).connect(equalizer)

    this.fail = new Synth(synthSettings).connect(distorter)
  }
}
```

I think it has to do with the fact that Tone is installed via NPM, if I try to reproduce it with the bundled JS, I works:
https://codepen.io/heine/pen/gxNEMj

**Comment by tambien** [comment] 2017-09-13 23:11
Usually you would get that kind of error if you had already disposed the instrument. 

Are you using some kind of build system like webpack or rollup?

I've got suggested setting with webpack [here](https://github.com/Tonejs/Tone.js/wiki/Installation#webpack) which work for me. It might be the fact that you're starting all of your modules with 'tone/' whereas i usually just add the 'tone' folder to the search path (so that it can also resolve internal dependencies).

**Comment by chlab** [comment] 2017-09-14 09:41
I just tried that, modules are now loaded like so:

```
import Synth from 'instrument/Synth'
import PolySynth from 'instrument/PolySynth'
import Distortion from 'effect/Distortion'
import Filter from 'component/Filter'
```

The error occurs here:

```
Tone.Gain.prototype.dispose = function(){
		Tone.Param.prototype.dispose.call(this);
		this._gainNode.disconnect();
		this._gainNode = null;
		this._writable("gain");
>>>		this.gain.dispose();
		this.gain = null;
	};
```

`this.gain` seems to be undefined.

**Comment by tambien** [comment] 2017-09-14 14:42
`this.gain` must be disposed somewhere else. Sometimes i create aliases members belonging to other classes like for example `this.volume = this._gainNode.gain` and then when `this.volume` is disposed it might create that condition. It's strange that it's only appearing when using through node_modules. 

What is the stack trace for the error?

**Comment by chlab** [comment] 2017-09-14 14:48
Indeed.
This is the stacktrace:

```
504:67 Uncaught TypeError: Cannot read property 'dispose' of undefined
    at Tone.Gain.dispose (504:67)
    at Tone.Volume.dispose (543:88)
    at Tone.PolySynth.Tone.Instrument.dispose (607:89)
    at Tone.PolySynth.dispose (609:242)
    at eval (557:487)
```

**Comment by tambien** [comment] 2017-11-29 21:41
any resolution on this issue? Going back to your original question, what do you mean by "bundled JS" vs "installed via NPM"? If the build you mean what's available [here](https://tonejs.github.io/build/Tone.min.js), that should be identical to the corresponding version published to npm.

**Comment by schtibe** [comment] 2017-12-07 08:06
Nope, not really, I just caught the exception and moved on, which was good enough for that project.

**Comment by tambien** [comment] 2018-01-09 16:25
I still haven't been able to recreate this issue. 

I think the straightforward solution to this would be to import classes from the built version like so (which can be npm installed): 

```javascript
import Tone, { Synth, Freeverb } from 'tone'

const synth = new Synth()
// ...etc
```

Also, [Tone.Gain](https://github.com/Tonejs/Tone.js/blob/dev/Tone/core/Gain.js#L56) has changed subtly since the version that you're using, which i think may also have fixed the problem. 

Closing for now. Please reopen if you're still experiencing the issue on the dev Tone.js (with a link to reproduce if you can!). The dev version can be installed like so: `npm install tone@next`

**Closed by tambien** 2018-01-09 16:25 UTC

**Comment by rayfoss** [comment] 2019-07-23 20:10
@tambien here's an online version with the latest package that has the same issue reproduced https://codesandbox.io/s/tone-bug-259-jfv48
