### ISSUE TITLE
Deprecation of dezippering in Chrome

### ISSUE THREAD

**Issue by 32u2** [Tonejs/Tone.js#288] opened 2018-01-03 09:36 UTC
As per https://bugs.chromium.org/p/chromium/issues/detail?id=496282, Chrome is to remove dezippering. The deprecation messages shown are as follows:

> [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed.
> [Deprecation] StereoPannerNode.pan.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed.
> [Deprecation] BiquadFilterNode.frequency.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed.
> [Deprecation] BiquadFilterNode.Q.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed.
> [Deprecation] OscillatorNode.frequency.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed.
> [Deprecation] OscillatorNode.detune.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed.
> [Deprecation] BiquadFilterNode.detune.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed.
> [Deprecation] BiquadFilterNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed.

**Comment by tambien** [comment] 2018-01-03 19:19
duplicate of #286

**Closed** 2018-05-19 21:32 UTC
