### ISSUE TITLE
When playing a sync Player using start, would occasionally get a null property error

### ISSUE THREAD

**Issue by jonbro** [Tonejs/Tone.js#302] opened 2018-02-08 03:23 UTC
Was getting this error:

`Uncaught TypeError: Cannot set property 'offset' of null at t.Player.t.Source.start (Tone.min.js:9)`

when doing the following code:
```
var apple = new Tone.Player({
    url: "apple.wav"
}).connect(Tone.Master).sync();
// then repeatedly calling
apple.start();
```
it wasn't a 100% of the time, and in fact was pretty infrequently, but it would be nice to have it fail gracefully if it hits a null in there.

apologies for not having a non-minified version of the project with this bug.

**Comment by tambien** [comment] 2019-01-09 23:06
This took me a while to take a look at, but i can't reproduce it. maybe it's fixed in the latest version: 

https://jsfiddle.net/stp9zqmf/3/

**Closed** 2019-01-09 23:31 UTC
