### ISSUE TITLE
Transport pauses in the Background

### ISSUE THREAD

**Issue by damonholzborn** [Tonejs/Tone.js#124] opened 2016-02-18 17:27 UTC
Moving this conversation from Twitter so we can talk in more than 140 characters…

Brief summary: I asked why the Transport in r6 stops running in the background and the answer was the move from the deprecated JSNode to animation frame.

This seems to me to be a significant limitation. It is a show-stopping issue for many use cases, and I don’t think this problem would surface merely in weird outlying cases. I can think of many reasons why one couldn’t just schedule things ahead of time: step sequencers, arpeggiators, drum machines, (basically, anything that loops), systems that interact with MIDI, algorithmic processes, networked apps. Also, I’m not sure how one would work around this given that it would be unknown when, and for how long, the app would stay in the background.

Overall, I think Tone is incredibly powerful. You’ve done great work here and I’m really appreciative of what you’ve built and shared. It is a fantastically well thought out system that can enable building useful tools for music creation (in addition to many other use cases). But it seems to me that this issue considerably cripples the ability to use Tone (or, at least the Transport) for many common use cases. It may seem silly to think about using the browser for serious music creation, but I think we are actually to a point where we can start considering using it for more that just cute web toys.

**Comment by tambien** [comment] 2016-02-18 18:29
Thanks for moving the issue to github. much easier to respond here. I agree this is an important issue. 

Pre-r6 the Transport used the ScriptProcessorNode which (sort of) ran in the background, but the timing was sporadic at best. For a few reasons (including the depreciation of that node), r6 switched to requestAnimationFrame as the basis of Tone.Clock. 

The requestAnimationFrame spec says that it can be reduced or dropped when running in the background. I think the same is true for other background JS processing like setTimeout or setInterval. The browser makers don't want background js processes eating up CPU and battery; this is at odds with sound makers needing a way to generate audio in the background (which in the context of the WAA pretty much necessitates a reliable JS callback).

Maybe a timer within a Web Worker is going to work for this. I will look into it. A quick test on Chrome just now had some promising results. But i'm not sure how other browsers are going to handle it. I also found [this](https://gist.github.com/nick-thompson/4551106) gist from a few years ago with a similar approach.

**Comment by cncocnco** [comment] 2016-02-20 20:56
Great! Let me know if there's anything I can do to help or test.

**Comment by agoode** [comment] 2016-03-10 04:06
Take a look at https://github.com/cwilso/metronome for an implementation of a WebWorker-based scheduler.

**Comment by JackCA** [comment] 2016-06-03 03:07
@tambien glad to see this is in the works for next release 👏 🎉

**Comment by odub** [comment] 2016-06-05 15:32
@tambien +1, looking forward to using this.

**Comment by arawind** [comment] 2016-11-06 17:56
Hi, I'm experimenting with r8 on chrome and seeing that the notes and the timings get jumbled up whenever the tab goes into the background. This is the case even with the examples and the demos, but they all seem to work fine on Firefox & Safari. 

Is this a known issue? I'm on a macbook, Chrome 54.0.2840.71. Posting here, since it seems like it's an issue with timing, but will create a new ticket if this is unrelated.

**Comment by tambien** [comment] 2016-11-06 23:36
Yes. I noticed this regression and filed a [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=646163) a while back. They seem to be working on it, but last i tested, it is not yet fixed in Chrome Canary. 

I will reopen this issue. 

Star [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=642321) to receive updates on it as they happen.

**Comment by tambien** [comment] 2016-11-24 18:42
Even with this new Chrome bug, i think i've addressed this issue in this commit: 84c1affe83f641192fcedee4201e3ae709be39e8 by automatically adjusting the lookAhead to the largest measured latency value. So when the page goes in the background, the lookAhead adjusts to about 1 second, which is the update rate while the tab is in the background, so events are computed in ~1 second chunks.

**Closed** 2017-01-08 23:37 UTC
