### ISSUE TITLE
Tone.Offline generated audio falls apart for >30s Audio

### ISSUE THREAD

**Issue by Awendel** [Tonejs/Tone.js#551] opened 2019-10-03 19:45 UTC
I'm generating Audio within Tone.Offline with a Sampler playing a Pattern
(I have to load the buffer samples externally because of an existing bug where Sampler can't be created within Tone.Offline, which hopefully will be fixed soon)

I'm taking the created Buffer and playing it with Tone.Player() upon its creation.

This works fine for recording between 15s-40s, howeever, anything longer (> 120s) than that seems to render, but the player just doesn't seem to play it.

Is there any existing bug known around Buffers that are perhaps too large or that the playback falls apart?

I could link to a live example tomorrow if folks are unable to reproduce the issue.

**Comment by tambien** [comment] 2019-10-03 20:32
Thanks, please include a live example of the bug when you have a moment

**Comment by Awendel** [comment] 2019-10-04 08:18
No problem:

https://jsfiddle.net/awendel/5j69de8b/16/

the top 2 variables can be modified to change the duration of the recording,
as well as toggle between playing a pattern & just repeatedly triggering a note.

**Comment by tambien** [comment] 2019-12-14 17:23
Seems to be fixed in the latest version of `tone@typescript`. 

Here's a validation created from a modification of your code: https://codesandbox.io/s/offline-rendering-test-2vw9r

**Comment by Awendel** [comment] 2019-12-14 19:42
Glad you were still working on it!
It sure seems a lot more robust now. What was the nature of the issue?

And how stable is the typescript branch for Production? Can all the main components be used without worry?

I played around some more with your modified example and observed quite a strange thing:

The sample works very well for 120s, but when I got up in duration, say 360s or 500s, I can see the CPU rapidly scheduling the notes and creating the Audio buffer (CPU load > 80% and the whole thing is parsed within a matter of seconds).

Yet then there seems to be a sort of "silence" where the CPU doesn't seem to do any work (at 0% load), yet the Audio Buffer doesn't play yet. This silence, I believe, is very small, almost unnoticable at 120s, yet goes up exponentially, the higher you go with duration (up to around 1 MINUTE of silence for 360s) before the playback kicks in.

Any idea what could cause this?

**Comment by tambien** [comment] 2019-12-14 22:05
i'd say the typescript branch is fairly stable. far less tested in production environments than `@next` or `@latest`, so use at your own risk. Will likely be merged into `next` soon. 

The compute time scales with the number of nodes, scheduled events and the duration being rendering. Not sure about the silence you're referring to. The process for scheduling generating a buffer with `Offline`:
1) Invoke the callback function and create all of the nodes in the function
2) Iterate over the timeline and schedule all events that are scheduled to the Tone.Transport
    * This part happens asynchronously using a setTimeout to not block the main thread #436
3) Render the audio buffer using `offlineAudioContext.startRendering()`

Step three is maybe where you're experiencing the "silence", but that part is a native call, so i don't have any control over what happens there.

**Comment by MaxLaumeister** [comment] 2019-12-22 05:40
I was having the same issue and updated my code to `tone@typescript` per the recommendation in this thread, and the issue is fixed now for me.

Thank you @tambien for your work on this awesome library. I'm looking forward to submitting my project as a demo when it's done!

**Comment by tambien** [comment] 2020-01-20 04:24
I think this should be fixed now in 'dev'. Closing this issue. thanks @MaxLaumeister for confirming.

**Closed by tambien** 2020-01-20 04:24 UTC
