### ISSUE TITLE
Source#_state.memory default

### ISSUE THREAD

**Issue by odub** [Tonejs/Tone.js#192] opened 2017-01-30 14:51 UTC
Hi,

I've been working on an audio player using the Tone `Transport` and `Player` classes. A `Player` instance is synced to the `Transport`. The `Transport` is set to loop to the length of the playback buffer.

I notice when I set `Transport.position` or `Transport.seconds`, the player follows the instruction `n` times in accordance with [this default](https://github.com/Tonejs/Tone.js/blob/master/Tone/source/Source.js#L58).

After `n` times is reach, I get unexpected behaviours: setting the playhead backwards, the set `Transport.position` is ignored; setting the playhead forwards the playhead forks and the playback overlaps itself.

This is my current proposed workaround, but it doesn't seem ideal.
```js
const player = new Player(audioBuffer);
if (player._state && typeof player._state === 'object') player._state.memory = 100;
```
Maybe, @tambien, you know a better way around the problem? Am I using the `Transport` and `Player` classes in an intended way?

I'm happy to help if there's a need for work to happen for this constraint be changed/removed in a future Tone.js version.

To see the issue in action, try setting the playhead more than 10 times here:
https://noise.fm/colortheory/flightless

Best,

Oscar

**Comment by jordanstephens** [comment] 2017-01-30 23:21
I don't think I see any major harm in doing this temporarily, but I would like to better understand what's going on here.

**Comment by tambien** [comment] 2017-01-31 04:37
Should be fixed now. You could also set `player._state.memory = Infinity` to make sure that the issue would never happen instead of just after 100 times. 

The issue here is a little complicated to explain, but i'll try to explain my thinking. All of this `_state` code is so that `source.state` correctly reports the source's state. 

The source's 'memory' is how many state change events it remembers into the past. 

For example, if you scheduled a bunch of events on a source: `source.start(0).stop(0.1).start(0.2).stop(0.3)`, each call to `source.state`, would look up the current AudioContext time and compare it against all of the events scheduled and return the scheduled state. It seemed like 10 was a reasonable amount to keep track of in the past. 

Also, when the player is _not_ synced to the Transport, it automatically schedules a stop event at the end of the buffer duration so that it correctly reports when it's done playing. So if a player's buffer were 0.5 seconds long and you scheduled `player.start(0)`, then `player.stop(0.5)` is automatically recorded to the state timeline so that `player.state` correctly reports `"stopped"` when time > 0.5. 

The problem is that the synced source wasn't pushing more 'start' events onto the state timeline, but kept pushing that 'stop' event until eventually the timeline filled up. And since the state timeline is a queue, the first 'start' event got pushed off after 10 times and so the player wouldn't report itself as 'started' and therefore not restart when the Transport position changes.

**Comment by jordanstephens** [comment] 2017-01-31 14:19
Thanks for the explanation @tambien

**Comment by odub** [comment] 2017-01-31 14:39
@tambien All clear and the commit seems like a good way to resolve this for future versions, appreciate it

**Closed** 2017-03-26 23:28 UTC
