### ISSUE TITLE
Part plays incorrect notes during first loop

### ISSUE THREAD

**Issue by jwarmerdam** [Tonejs/Tone.js#181] opened 2016-11-24 04:07 UTC
I'm trying to play some Parts together using a PolySynth, and during the first loop of the part (in chrome Version 54.0.2840.99 m) many of the notes will play using the previous note's pitch. Once the part loops the issue goes away. 

I'm using synth.triggerAttackRelease(note, duration, time);

If I leave out time, it plays the notes correctly, although with a few glitches.

https://jsfiddle.net/p113xz2k/

I've also tried scheduling the notes further in the future, but it didn't help. Any clue what I could be doing wrong?

**Comment by jwarmerdam** [comment] 2016-11-24 06:50
Actually, when I put other songs in it doesn't fix at the loop boundary, that was just a coincidence. The notes eventually correct after some time has passed.

**Comment by tambien** [comment] 2016-11-24 18:17
Very lovely song in the example. :)

I think the issue is caused by the spike in CPU typically when the page first refreshes. it usually takes a little time before everything is loaded and the page is fully ready to start processing audio. 

The quick fix for me if you want the song to immediately play on load is usually to schedule the start in the future, e.g. `Transport.start("+1")`. I would also advocate for starting on user input (like a play button) which would add a few moments of delay which is probably enough for the audio thread to catch up and works best on iOS and Safari.

**Comment by jwarmerdam** [comment] 2016-11-24 20:27
Thanks for the quick response. The version on my personal website starts on button press and seems to do the same thing whether I wait a while or not. I tried starting in the future as well. I guess I can try starting the transport significantly in the future (like +30 or something) and see if that helps.

**Comment by tambien** [comment] 2016-11-24 21:02
"+30" seems like too much. I just tried plugging in "+1" into Transport.start and i could hear that first note which seems to be lost sometimes without it.

**Comment by jwarmerdam** [comment] 2016-11-25 05:16
I think you are hearing a different issue than I am. When I open the example in Chrome 54 (on PC), most of the notes for the first 20 seconds or so have the wrong pitch (timing and duration are correct). It seems like pitch updates are just not applying. I tried it out on a MacBook in Chrome 52, and Safari 9.3, and both of those work fine outside of some startup glitches. Seems like maybe its another Chrome 53+ issue.

**Comment by pikurasa** [comment] 2016-11-27 20:14
This may be related to a bug that has been creeping in for our project, which uses tone.js: https://github.com/walterbender/musicblocks/issues/295 I am just putting this note here now for the record, but need to investigate further. Basically, we are getting the wrong notes during playback (although the log for tone.js seems to think they are the right notes...)

**Comment by pikurasa** [comment] 2016-11-27 20:30
> I tried it out on a MacBook in Chrome 52, and Safari 9.3, and both of those work fine outside of some startup glitches. Seems like maybe its another Chrome 53+ issue.

This seems to ring correct so far. If I test in Chromium (Version 54.0.2820.0 (64-bit) and version 53.0...), I get the issue. If I try FireFox, I do not seem to reproduce the issue. I did not record what versions that the Windows and Mac machines at A^2 were running when we did the workshop, but they were probably "up-to-date" (53+).

Other Note: FireFox sound is more distorted than Chromium-family.

@tambien ...so is the problem with how Chromium handles tone.js or with how tone.js instructs chromium?

**Comment by tambien** [comment] 2016-11-28 21:09
I agree that this sounds like it's related to the Chrome bug and this issue: #163

Looking at the issue that I filed, it seems like it is being addressed, but will probably still take a little while to make it's way into the current version of Chrome. I put a small patch into Tone.js r8 which mitigates the issue, but it won't be fixed until Chrome fixes this bug.

**Comment by tambien** [comment] 2017-01-08 19:18
Duplicate of #163. Moving the conversation back over there.

**Closed by tambien** 2017-01-08 19:18 UTC

**Comment by pikurasa** [comment] 2017-01-08 21:53
> Looking at the issue that I filed, it seems like it is being addressed, but will probably still take a little while to make it's way into the current version of Chrome. I put a small patch into Tone.js r8 which mitigates the issue, but it won't be fixed until Chrome fixes this bug.

Is it being addressed?

The last I heard on the issue that I filed, they were not taking any action because they did not understand the issue well enough (I can give repro steps for the bug's effect in our program, [Music Blocks](https://github.com/walterbender/musicblocks/), but they wanted more).

The issue I filed is at: [https://bugs.chromium.org/p/chromium/issues/detail?id=671591#c7](https://bugs.chromium.org/p/chromium/issues/detail?id=671591#c7)

**Comment by pikurasa** [comment] 2017-09-13 20:31
Hi. One of the Chromium developers closed the issue, FYI. https://bugs.chromium.org/p/chromium/issues/detail?id=671591#c12

If you think it is still an issue, please reopen and communicate with their developers. Thanks!
