### ISSUE TITLE
Synchronization issue between two GrainPlayer

### ISSUE THREAD

**Issue by davidli09** [Tonejs/Tone.js#544] opened 2019-09-19 09:02 UTC
I have a synchronization issue between two GrainPlayers.

I need to play the 2 audio files - one is music file and the other one is recorded blob using HTML5 MediaStream. At the end of the recording, I need to adjust the synchronization to make it sound at the same time. And the thing here is two players are not playing consistently. There's a slight delay every time I play the music and it's not consistent. 

Here's the link.
http://54.65.240.103/recorder-test/
In this test app I use 2 audio files - Mp3 and Wav. Mp3 file is 180 seconds long and Wav file is 120 seconds. If you click `Play/Pause` button a few times (maybe more than 10 times), you can hear the difference. 

Please let me know how to fix this issue. 
Thanks in advance.

**Comment by tambien** [comment] 2019-09-19 15:47
Thanks for the issue. i can hear the offset between the two tick sounds. Glancing through the code i've got a couple of things that you could try out to help figure out where the issue is coming from.

I see that you're starting the players always at 0 in this line:
```js
play(startTime = 0) {
    // Tone.Transport.start();
    this.player.start(0, this.offset + startTime);
 }
```

This basically starts them immediately and it's possible that some small amount of time has passed between the two subsequent calls which would lead to them starting at different times. A technique to better ensure sync'ed timing is to start them at exactly the same time in the future. 

So you can use something like Tone.now() which will give you the audio context clock plus a small look ahead time. And pass the same time value into both the 'music' and 'voice' start methods. 

Might look something like this:

```js
const startTime = Tone.now()
this.music.start(startTime)
this.voice.start(startTime)
```

My other question is about how you're using the HTML5 Media Stream. The HTML5 MediaStream and media recorded can't be scheduled in a precise way like the rest of Web Audio can. Take a look at [this issue](https://github.com/Tonejs/Tone.js/issues/524#issuecomment-518761418)

**Comment by scriptmaven** [comment] 2019-09-20 08:47
@tambien Thank you for your reply. I tried what you suggested and it improved the synchronization a bit but it still happens. And I've already checked this [link](https://github.com/Tonejs/Tone.js/issues/524#issuecomment-518761418) before.

So here's how I use the MediaRecorder. 
At first, use records both video and audio using MediaRecorder while hearing the music. 
```javascript
this.recorder = new MediaRecorder(...);
...
this.recorder.start();
```

After user stops the recording, I create the blob using the recorded result.
```javascript
recorder.ondataavailable = e => {
    this.chunks.push(e.data);
};
...
const blob = new Blob(this.chunks, { type: this.mimeType });
```

And then I use this blob and music file to test the synchronization and adjust it as you can see in the above link. 

And I also need to play the recorded video at the same time. 
Let me know your thoughts on this. 
Thanks.

**Comment by tambien** [comment] 2019-09-20 22:05
Thanks for the issue and test case. I think the issue was some subtle ways in which the total offset was being handled. It seems to get off after a while. I am now using a more reliable counter for offset which is the internal clock's tick counter which is computed using `Tone.TickSource`. 

Should be fixed in `tone@14.3.45`. 

Here's an example running that code: https://codesandbox.io/s/synced-gain-player-example-qew5m

I create short blip  through the offline context and then play it out of both GrainPlayers. Even after many starts and stops, they are still synchronized. Let me know if you're able to test this with your own code. `tone@^14` has a number of changes from the previous version because of the typescript conversion currently underway. hopefully there aren't too many upgrade pains.

**Comment by scriptmaven** [comment] 2019-10-04 09:34
@tambien Thank you the example. Until you release the new version, I am going to use HTML5 Audio element to adjust the sync between two music files.

Anyway, there's another issue with GrainPlayer. While mp3 file is being played using GrainPlayer, I could hear tremolo effect sometimes which results in delaying the audio a bit. 
Not sure if I described the problem correctly, but it's something like GrainPlayer is loading audio data from the server and stops for a few miliseconds.

Here's the test file link attahched - [file](http://54.65.240.103/recorder-test/test.mp3)

**Comment by tambien** [comment] 2019-10-04 15:44
To me, it sounds like an artifact of the way that the GrainPlayer works with the settings that you've got it on. GrainPlayer breaks up the audio into short grains (configurable by the `grainSize`) and plays these grains back with short cross-fades between them with some overlap. These settings are all configurable. The short grains are how it's able to achieve the pitch shift and time stretch functions. It should be possible to configure your settings so that this effect is less prominent. 

If you use the Player instead of the GrainPlayer, it'll just play the audio back without any modification, which sounds like it might be what you're looking for in this case.

**Comment by scriptmaven** [comment] 2019-10-04 15:50
At first, I tried Player, but pitch shift was not working well compared to the GrainPlayer. 
Because of the pitch shift performance issue, I switched to the GrainPlayer and after that number of issues arose such as this tremolo, delay, synchronization and so on.

What do you recommend to this kind of Karaoke app? There's background music being played, user sings a song using microphone and at the same time record the video. 
While singing they need to adjust the pitch shift, reverb, and other few settings which are provided by this library - Tone.js.

Should I switch back to the Player again?

Thanks.

**Comment by tambien** [comment] 2019-10-04 15:59
Tone.js has a few ways to do pitch shiftings since there are so many different techniques out there for doing this kind of thing. Each with its own affordances and limitations. I think the technique you choose is going to depend on the content of your audio since there's not really a one-size-fits-all solution. 

I'd recommend if you're playing the audio back with no pitch shifting at all, choose the Player. If you'd like some pitch shifting without time stretching, GrainPlayer is a good option, but you should play with the settings depending on the amount of pitch shifting you want and the audio content.

**Comment by scriptmaven** [comment] 2019-10-04 16:03
Pitch shifting is necessary so it seems like I need to stick with GrainPlayer then. 
Regarding tremolo and sync issues, I need to change the GrainPlayer settings constantly and find the best values on my own?

Just FYI, pitch shift range is [-6, 6] and audio content is generally 3-5 minutes.

**Comment by tambien** [comment] 2020-01-20 04:23
Should be fixed now in 'dev' since typescript branch is merged into 'dev'.

**Closed by tambien** 2020-01-20 04:23 UTC
