### ISSUE TITLE
Typescript Branch: Cannot be imported into Safari <= 12

### ISSUE THREAD

**Issue by JackCA** [Tonejs/Tone.js#601] opened 2020-01-08 19:55 UTC
I'm seeing an issue in my exception handler for users on Safari 12 and 11 at this line in the `build/esm/index.js` file:

` export var now = getContext().now.bind(getContext());`

The full stack trace is as follows:
```
TypeError: undefined is not an object (evaluating 'a.connect(n).connect')
  at ? (/app/node_modules/standardized-audio-context/build/es2018/helpers/test-audio-node-disconnect-method-support.js:14:1)
  at initializePromise([native code])
  at Promise([native code])
  at test(/app/node_modules/standardized-audio-context/build/es2018/helpers/test-audio-node-disconnect-method-support.js:2:1)
  at cacheTestResult(/app/node_modules/standardized-audio-context/build/es2018/factories/cache-test-result.js:12:1)
  at super(/app/node_modules/standardized-audio-context/build/es2018/factories/audio-node-constructor.js:271:1)
  at audioDestinationNodeConstructor(/app/node_modules/standardized-audio-context/build/es2018/factories/audio-destination-node-constructor.js:10:1)
  at super(/app/node_modules/standardized-audio-context/build/es2018/factories/minimal-base-audio-context-constructor.js:13:1)
  at super(/app/node_modules/standardized-audio-context/build/es2018/factories/base-audio-context-constructor.js:4:1)
  at ? (/app/node_modules/standardized-audio-context/build/es2018/factories/audio-context-constructor.js:21:1)
  at Context(/app/node_modules/tone/build/esm/core/context/AudioContext.js:8:16)
  at getContext(/app/node_modules/tone/build/esm/core/Global.js:22:24)
  at call(/app/node_modules/tone/build/esm/index.js:12:18)
  at __webpack_require__(webpack/bootstrap:86:1)
  at call(/app/node_modules/tinyqueue/index.js:86:1)
  at __webpack_require__(webpack/bootstrap:86:1)
  at call(./state/sanitizer.ts:35:42)
  at __webpack_require__(webpack/bootstrap:86:1)
  at call(/app/node_modules/next-redux-wrapper/es6/index.js:77:41)
  at __webpack_require__(webpack/bootstrap:86:1)
  at regFn(/app/node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js?6ac4:3:17)
  at register(/app/node_modules/next/dist/client/page-loader.js:15:57)
  at push(/app/node_modules/next/dist/client/page-loader.js:17:263)
  at call(/app/node_modules/next/dist/build/webpack/loaders/next-client-pages-loader.js?6ac4:2:1)
  at __webpack_require__(webpack/bootstrap:86:1)
  at checkDeferredModules(webpack/bootstrap:45:1)
  at webpackJsonpCallback(webpack/bootstrap:32:1)
  at global code(/_next/static/KgV7EMgldFzItZnOHhv4n/pages/_app.js:1:51)
```
[This public sentry exception will help with source maps](https://sentry.io/share/issue/c9d6bd2d71794c288d0add4975d797c1/)

I am proactively using the [`isSupported`](https://github.com/chrisguttandin/standardized-audio-context#issupported) method from standardized-audio-context to inform users that their browser is not supported, but I'm unable to catch this because it happens simply from importing the Tone.js library.

Is there a way to capture this without async importing Tone and catching the error?

**Comment by tambien** [comment] 2020-01-12 22:34
i wonder if it has to do with standardized-audio-context's supported browser. Their goal is to only keep up with current and future browsers, they support Safari 12.1+ and not earlier. Can you check if this works on Safari 12.1? If that's the case, we should try to find out what's changed between 12 and 12.1 and see if it's easy enough to make a shim for.

**Comment by JackCA** [comment] 2020-01-13 03:16
I can confirm that I've never seen it on Safari 12.1, only <= 12.0.1 -- but the key thing here is that `standardized-audio-context` gives us the ability to know beforehand whether the current browser is supported or not.

Ideally, Tone.js uses that method before running any code that could break in these browser versions and stops the library from initializing, and would also ideally give the developer notice that it won't work.

I think the issue with that is that the check is async and I don't believe Tone.js has any sort of "initialize" method.

cc @chrisguttandin if you have any thoughts

**Comment by chrisguttandin** [comment] 2020-01-13 12:50
Yes `isSupported()` returns a promise. Most of the tests are synchronous but [4 of them are not](https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/factories/is-supported-promise.ts#L32) which is the reason why the result can only be returned as a promise.

I think the issue reported here is caused by the fact that `connect()` was not chainable in older versions of Safari. An easy fix might be to not rely on that feature internally in Tone or to somehow include the [test for it](https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/factories/test-audio-node-connect-method-support.ts). However that won't fix the general problem.

**Comment by tambien** [comment] 2020-01-13 17:04
@chrisguttandin I can't find any instances where i use that connection chaining in the library. 

@JackCA waiting for my browserstack account to be approved so i can test some things out.

**Comment by JackCA** [comment] 2020-01-13 17:41
Understood, thanks @chrisguttandin. Just to reiterate: I’m not concerned about having Tone.js work in these versions, just think it’s important to be able to capture that fact. 

@tambien yeah that’s a good idea. Hope they have some open source deal

**Comment by chrisguttandin** [comment] 2020-01-13 21:16
I guess the error is been thrown because I don't have any safety net in standardized-audio-context for unsupported browsers. Sure, there is the `isSupported()` function but the other code just fails unexpectedly when there is some missing functionality. I will make sure that at least the functionality tests are guarded. That should hopefully fix this issue.

**Comment by chrisguttandin** [comment] 2020-01-14 11:15
Does the error still persist with v23.1.2 of standardized-audio-context?

The new version does now catch any error that happens during feature support tests. Any error is just interpreted as a false result.

**Comment by JackCA** [comment] 2020-01-14 17:37
I've deployed the updated version and will monitor

**Comment by tambien** [comment] 2020-01-20 04:40
@JackCA did it work?

**Comment by JackCA** [comment] 2020-01-21 19:16
@tambien @chrisguttandin: unfortunately, it looks like it's still happening, even with the latest version of standardized-audio-context. Here's an updated [sentry stacktrace](https://sentry.io/share/issue/ae2ad8bca5f54ce480c792cb603fcfe8/)

**Comment by chrisguttandin** [comment] 2020-01-21 19:44
For some reason at least the source-map doesn't point to v23.1.2 of standardized-audio-context. If you compare the code snippet in the stacktrace of `build/es2018/factories/cache-test-result.js` with the version on npm (https://unpkg.com/browse/standardized-audio-context@23.1.2/build/es2018/factories/cache-test-result.js) it misses the `try/catch` clause.

Could there be an older version in the cache somewhere?

**Comment by JackCA** [comment] 2020-01-21 20:30
@chrisguttandin good catch. I think it's an issue with my Sentry grouping configuration and the stacktrace is only collected from the first instance of the exception (which happened prior to the v23.1.2 upgrade).

I'm changing the grouping strategy and redeploying so we can hopefully get a better/different stacktrace.

**Comment by JackCA** [comment] 2020-01-27 01:27
I haven't seen this pop up again so I think we're good!

**Closed** 2020-01-30 22:18 UTC
