### ISSUE TITLE
Synth.set("envelope", new Tone.Envelope()) error

### ISSUE THREAD

**Issue by timpulver** [Tonejs/Tone.js#213] opened 2017-03-14 16:31 UTC
When trying to set a synth’s envelope using the following code I get an error:
```javascript
var synth = new Tone.AMSynth();
var env = new Tone.Envelope();
synth.set("envelope", env);
```

Error:
```javascript
Uncaught TypeError: Failed to set the 'value' property on 'AudioParam': The provided float value is non-finite.
    at t.TimelineSignal.set (tone.min.js:8)
    at t.AmplitudeEnvelope.s.set (tone.min.js:8)
    at t.AMSynth.s.set (tone.min.js:8)
    at <anonymous>:3:7
```
The following works:
```javascript
var synth = new Tone.AMSynth();
var env = {
    'attack': 0.1,
    'decay': 0.1,
    'sustain': 0.1,
    'release': 0.1,
};
synth.set("envelope", env);
```

**Comment by tambien** [comment] 2017-03-14 17:03
Duplicate of #202. 

`set` is only for setting attributes; it can't replace members of the instance. You can access the envelope of the synth directly through `synth.envelope`, then set it's attributes individually (`synth.envelope.attack = 0.1`) or with an object (`synth.envelope.set({'attack': 0.1})`) or use `set` with an member name and the value to set its attributes (`synth.set('envelope', {'attack': 0.1})`). 

`set` is documented [here](http://tonejs.github.io/docs/#Tone.set).

**Closed by tambien** 2017-03-14 17:03 UTC

**Comment by timpulver** [comment] 2017-03-14 17:46
Sorry for the duplicate and thanks for the clarification!
So every time a Tone object is listed as a class member it can be accessed via `synth.get("envelope")` and directly via `synth.envelope`? Does it matter how it is accessed?

**Comment by tambien** [comment] 2017-03-14 18:34
No problem. 

Yes exactly. Class members can be accessed directly with `.` or using `get` or `set`. They are pretty much the same, but `get` and `set` can give you a terser syntax over directly accessing a member if you want to set/get many different members at once: 

```javascript
synth.set({
  detune : -10,
  envelope : {
    attack : 0.1
  },
  // ...etc
})
```
