### ISSUE TITLE
[Deprecation] BiquadFilterNode.frequency.value setter smoothing is deprecated

### ISSUE THREAD

**Issue by gaspard** [Tonejs/Tone.js#286] opened 2018-01-01 13:38 UTC
```
[Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
```

[chrome dezippering info](https://www.chromestatus.com/features/5287995770929152)

Both latest and dev build produce the warning (look in the console with Chrome Version 63.0.3239.84.

https://jsfiddle.net/3m9k17ef/ (latest release)
https://jsfiddle.net/kyqnbr7d/ (dev build)

**Comment by tambien** [comment] 2018-01-02 23:52
duplicate of #282 and #283

**Closed by tambien** 2018-01-02 23:52 UTC
