### ISSUE TITLE
all the images on https://tonejs.github.io/demos are broken

### ISSUE THREAD

**Issue by Pomax** [Tonejs/Tone.js#393] opened 2018-09-29 19:22 UTC
![image](https://user-images.githubusercontent.com/177243/46249705-558b0700-c3e2-11e8-861d-90f28e6c3cfb.png)

**Comment by tambien** [comment] 2018-09-29 19:34
just opened in an incognito tab and could not reproduce. could you try refreshing? maybe it was a temporary downed server or something. if it does persist, would you please open the console and paste in the error shown there?

![image](https://user-images.githubusercontent.com/1323402/46249795-0ef6d600-c3fd-11e8-8b58-fb48c9e2cf28.png)

**Comment by Pomax** [comment] 2018-09-30 03:45
Interesting, it looks like the new content blocking in Firefox goes "this site is trying to load a million images from a google drive. I'm blocking that".

**Comment by tambien** [comment] 2018-10-01 16:29
:(

i thought i had a clever system where users could submit projects through a form which get dropped directly in a drive that i could serve the images from without having to manually upload each demo. 

Is there any hint at a way around it? maybe there's a setting on Drive which would enable a work around, or deep link to the original image somehow to circumvent drive's image sharing link that they generated for me (which probably has tracking on it).

**Comment by Pomax** [comment] 2018-10-01 22:54
If Drive lets you "whitelist" your domain so that its cross-origin resource sharing header includes it, things should work. I have no idea if it has that option though =S

**Comment by tambien** [comment] 2018-10-13 15:43
going to close this, but will open placeholder issue on the tonejs.github.io repo to remind me to try and find some kind of work around

**Closed by tambien** 2018-10-13 15:43 UTC
