### ISSUE TITLE
Tone.Sequence skips the first note on specific browsers

### ISSUE THREAD

**Issue by sisyphus16** [Tonejs/Tone.js#403] opened 2018-11-16 10:38 UTC
Hello, and thank you for this awesome library!

I've been experiencing the issue #365 with Tone.Sequence even after updating to the latest release.
However I noticed the issue is happening on specific browsers, such as Chrome and Safari, and is not happening at all on Firefox Quantum (where everything is perfect).

If you run the [fiddle](https://jsfiddle.net/gabrielflorit/635a0c4g/16/) from #365 on Chrome/Safari/Vivaldi/Opera/etc you can still experience it.

It isn't systematical, but the first note is skipped definitely more than sometimes, especially in some cases: it looks like the faster the time and the longer the sequence, the greater the chances the 1st note is skipped. Check this out:
[https://jsfiddle.net/sisyphus16/6g3hxbza/](https://jsfiddle.net/sisyphus16/6g3hxbza/)
It's almost constant here. 

Hope this helps. Keep up the good work. And thanks again.

**Comment by tambien** [comment] 2018-12-02 18:09
thanks for the issue, but this is a duplicate of #365. the solution is to upgrade to `tone@next`, which has the fix.

**Comment by sisyphus16** [comment] 2018-12-03 09:41
> thanks for the issue, but this is a duplicate of #365. the solution is to upgrade to `tone@next`, which has the fix.

Hello, thank you for the reply.
I did in fact upgrade to 'tone@next' but I'm still experiencing the issue. 
I guess I have to be missing something and I feel sorry for that...
I ran `npm install tone@next` once again and I have `tone@13.3.11` and Tone.Sequence is still skipping the first note.

**Comment by sisyphus16** [comment] 2018-12-03 15:14
So, I guess you've probably thought that I hadn't run the update cause the fiddle had v12, my bad, but I did have an angular app up to date and that's why I reopened the issue.

Here is the updated fiddle with `tone@13.3.11`: https://jsfiddle.net/x7528rkh/2/
and the first note gets skipped.

Thank you in advance.

**Comment by tambien** [comment] 2018-12-03 16:16
my bad! you're totally right. slightly different issue than #365. including a fiddle always really helps clarify.

**Comment by tambien** [comment] 2018-12-16 18:00
I looked into this for a while, and i've found the cause of the problem, but i don't see any straightforward solution on the Tone.js-side of things. the issue is that without any arguments, `sequence.start()`, adds an event to the current tick on the timeline which is tied to the AudioContext time which runs in a separate thread. by the time the 'start' method has finished adding the event to the Transport's timeline, a small amount of time has passed in the AudioContext thread causing that event to now be in the past. the event is added to the timeline, but the timeline has already passed the event's scheduled time, so the event does not get invoked. 

The simple fix is to just schedule events slightly in the future to guarantee that they are added to the timeline on a future tick and do not get passed over.  [Here's an example](https://jsfiddle.net/x7528rkh/6/) where the start method is scheduled 100ms in the future to ensure that first event is heard.

**Closed by tambien** 2018-12-16 18:00 UTC
