### ISSUE TITLE
buffer.getChannelData(0) returns null on  Chromium: 77.0.3865.90 (Brave)

### ISSUE THREAD

**Issue by radio-alice** [Tonejs/Tone.js#549] opened 2019-09-30 02:06 UTC
Sorry if duplicate - couldn't find anything on this.

I noticed when trying to create a PingPongDelay, played around in the browser console until I got down to the buffer.getChannelData call in Context.js.
It looks like the buffer is initializing correctly, and has a channel, but getChannelData not working.
Tested on Firefox and it works fine there.

see logs when this fiddle is run:
[https://jsfiddle.net/m201gh4j/](https://jsfiddle.net/m201gh4j/)
(broken for both tone/next and tone/latest)

Thanks for all the hard work you've put into this - def one of the coolest libraries out there :)

**Comment by radio-alice** [comment] 2019-09-30 02:12
Also this makes no sense to me but it might help: the issue doesn't appear when using parceljs to serve files locally. It does still appear when using parcel build or just linking the library directly in an html file.

**Comment by tambien** [comment] 2019-09-30 15:10
Thanks for the issue. When i run the code i don't see any errors in the console. can you point me to the steps you took to reproduce the error that you got? 

Here's a little demo of loading a buffer and printing `getChannelData(0)` to the console.

**Comment by radio-alice** [comment] 2019-09-30 16:08
The fiddle works for me in firefox, prints `null` in Brave (Chromium 77). I downloaded Chrome and it works there – looks like it's an issue with Brave/their version of Chromium. Probably not worth your time!

**Comment by tambien** [comment] 2019-09-30 16:42
interesting. i'm seeing that too on Brave. My guess is it's a content security policy. In this case since the buffer is loaded from another server, it will not let you inspect the bytes, but the buffer is still usable in that it'll let you play the audio, just not look at the data. 

I just tested the same code out running on a local server with Brave and i was able to download the buffer and `getChannelData`. So that support my theory about the heightened security sandboxing which Brave adds.  

The solution is to make sure that you're downloading audio from the same origin as your server. Let me know if you're able to validate my theory by testing audio files downloaded from the same origin.

**Comment by radio-alice** [comment] 2019-09-30 21:28
I wasn't loading a buffer from an audio file though– I'm pretty sure it was creating one in memory as part of calling `new Tone.PingPongDelay` (all on the same frontend).

Not sure if I'm misunderstanding you though?

**Comment by tambien** [comment] 2019-09-30 21:32
maybe i misunderstood as well. How are you generating the buffer exactly? 

If you could provide a code example of how you reproduced the error, that'd be helpful. then we'd know we're talking about the same thing. :)

**Comment by radio-alice** [comment] 2019-09-30 22:18
yeah so the fiddle I linked at the top does have the error for me - I was trying to boil it down to what call was actually failing.

My code that was originally producing the error was:
`const ppDelay = new PingPongDelay(0.5, 0.5).toMaster()`

but it invokes `buffer.getChannelData(0)` somewhere in the creation of the delay object, which returns null which is what causes it to throw

Does that make sense? sorry I should have started at the highest level.

**Comment by tambien** [comment] 2019-09-30 22:36
ok i see now where that's coming from. yeah still seems like this is a content security policy because of Brave's heightened javascript security. Are you getting this same error when you're running your code locally on Brave? because it works fine for me as long as all the code originates from the same origin. 

For example [this code](https://tonejs.github.io/examples/pingPongDelay.html) runs fine on brave which is using a PingPongDelay but where all of source code originates from the same source.

**Comment by radio-alice** [comment] 2019-09-30 23:43
with device recognition shields up: works in localhost, doesn't work when just opening local file, doesn't work in production (pretty sure all coming from same origin but netlify might be doing something funky)

with those shields down: works everywhere

I'm not too worried about supporting brave with those specific shields up (I think they break threejs as well), so you can feel free to close this 

thanks for the help :)

**Comment by tambien** [comment] 2019-10-01 22:25
i'm glad that we have this documented here, but if a user has a security/privacy policy set on their browser which blocks some Web Audio features, i don't think there is much that we can do to support Tone.js in their environment. 

Going to close this issue. If there are workarounds or suggestions, or some documentation on which features do and don't work, it'd be great to link to those somewhere.

**Closed by tambien** 2019-10-01 22:25 UTC
