### ISSUE TITLE
this question in latest version 

### ISSUE THREAD

**Issue by himiten** [Tonejs/Tone.js#225] opened 2017-03-30 10:12 UTC
code just this:
```javascript
let Tone=require("tone");
document.getElementById("play").addEventListener("click",()=>{
    let synth = new Tone.Synth().toMaster();
    synth.triggerAttackRelease("C4", "8n");
});
```

 **in webpack pack and run in browser,then occurred:**
**Uncaught TypeError: Tone.Synth is not a constructor**

**Comment by himiten** [comment] 2017-03-30 10:14
``let Tone=require("tone");
document.getElementById("play").addEventListener("click",()=>{
    let synth = new Tone.Synth().toMaster();
    synth.triggerAttackRelease("C4", "8n");
});

**Comment by himiten** [comment] 2017-03-30 10:16
**in webpack pack and run in browser,then occurred: Uncaught TypeError: Tone.Synth is not a constructor**

**Comment by tambien** [comment] 2017-04-01 16:42
I'm unable to reproduce this error. I use webpack with Tone.js all the time. 

Just to confirm: there's no error when you're building with webpack?

**Comment by tambien** [comment] 2017-05-01 19:52
@himiten any updates? closing for now.

**Closed by tambien** 2017-05-01 19:52 UTC
