### ISSUE TITLE
Tone.Part + Tone.Players glitches when exporting audio from Tone.Offline

### ISSUE THREAD

**Issue by Andy671** [Tonejs/Tone.js#630] opened 2020-03-16 01:07 UTC
Hey! Thanks for the great music package! 

I've found an issue with **Tone.Offline**. I am trying to render .wav file of my music that is coming from **Tone.Players** that was created from multiple Buffers. The sound glitches and doesn't play at all after a few seconds. The moment when it stops -> happens randomly.

Here is the simplest possible bug illustration:
Case 1: plays audio with default **Tone.Transport** and it works great.
Case 2: exports broken .wav file from buggy **Tone.Offline Transport**.
https://jsfiddle.net/Andy671/rt1kgzbp/86/

Everything worked fine when I used **Tone.Sampler** as a source.
For now, in my project, I do the workaround by using **Tone.Sampler** for my sounds. But I hope you will resolve the issue in the future!

**Comment by tambien** [comment] 2020-03-16 01:16
This seems like a duplicate of #551. Can you try to update to `tone@next` and see if that fixes it for you?

**Comment by Andy671** [comment] 2020-03-16 11:22
@tambien you are right! It works with the latest tone.
Here is the updated snippet for anyone who is looking at how it works in the tone@next: https://jsfiddle.net/Andy671/rt1kgzbp/102/

By the way, do you have any estimates on when a new Tone would be available at the stable branch?

Also, I experience one more non-fatal issue with **getTicksAtTime**. I am using React, and when some ui changes occur the same time when Transport triggers audio - this can happen. I can't reproduce it in the issue, but maybe you can give me a hint about what can cause it?

**Closed** 2020-03-16 11:23 UTC
