### ISSUE TITLE
Unstable note playing when scheduling at time 0

### ISSUE THREAD

**Issue by stephaneeybert** [Tonejs/Tone.js#649] opened 2020-04-17 11:59 UTC
I noticed that when starting the measure index at 0 the first measure is often, but not always, skipped, and the notes start playing only from the second measure.

But when starting the measure index at 1 then the first measure is always played and no notes are ever missed.

It took me a little while to notice this instability.

```
Tone.Transport.scheduleOnce((measureStartTime: any) => {
}, measureCounter + 'm');

```

**Comment by tambien** [comment] 2020-04-17 16:59
Could you post a jsfiddle or a way to reproduce this issue? I am unable to reproduce the issue with your above code. 

There is usually instability with the AudioContext as soon as the page loads, it's always best to start the Transport from a button click (which also solves common Autoplay pitfalls and will work more consistently across browsers) instead of just on page load.

**Comment by stephaneeybert** [comment] 2020-04-21 06:30
I experience the issue, even long after the page has loaded, even after multiple play and stop of the soundtrack.

I will now try to create a live example and come back with it.

**Comment by stephaneeybert** [comment] 2020-04-21 09:45
Hello, I have now made a live [example](https://stackblitz.com/edit/angular-tone-4hcdqg).

**Comment by tambien** [comment] 2020-04-21 18:53
Looks like your example is using `tone@0.12.66`. Could you update to `tone@latest` or `tone@next`? It's possible this issue has already been fixed in subsequent versions

**Comment by stephaneeybert** [comment] 2020-04-22 03:03
I upgraded the `tone` dependency of the example to `^13.8.25` and still observed the exact same issue after reloading the example.

I have the same dependency on my project.

I then tried to do an `npm i tone@latest` and it updated a dependency;
```
+ tone@13.8.25
updated 1 package and audited 30268 packages in 67.818s
```
but my `package.json` file did not change as it already had that same dependency version.

I then tried to do an `npm i tone@next` and it updated a dependency, and my `package.json` file changed:
+ tone@14.6.0

I upgraded the example with the same version and the issue went away there.

On my app the issue also went away.

But there was some other issue showing up, the events seem to not be cancelled properly. On a replay the sound becomes garbled. I can see the error message in the console: `Max polyphony exceeded. Note dropped`. It's a show stopper. I have to revert to the previous stable version. No worries.

**Comment by tambien** [comment] 2020-04-23 14:07
The max polyphony is initially set to 32 i think, but you can pass in an argument to the constructor to increase that. But if you're exceeding 32, it might be an issue that the notes aren't being released. 

If the original issue is fixed in `tone@next`, i suggest we resolve the issue and create another issue if you're unable to solve the PolySynth `max polyphony` issue

**Comment by stephaneeybert** [comment] 2020-04-23 18:07
I have used at most 4 voices in a poly synth, so I'm surprised it hit the 32 maximum. I have never been above 4 in my synth configurations. Let's see if `tone@next` fixes this.

**Comment by tambien** [comment] 2020-04-28 19:16
@stephaneeybert any updates on the original issue?

**Comment by stephaneeybert** [comment] 2020-05-01 13:01
I just installed the tone@ dependency again in my application.

The sound came out again poorly, with some clearly heard static, like some radio received audio. Stopping the play did not release all of the notes and some were left triggered. I had the same results with the following synths:

```
    const synth: any = new Tone.PolySynth(Tone.Synth, {
      "volume" : -8,
      "oscillator" : {
          "partials" : [1, 2, 5],
      },
      "portamento" : 0.005
    }).toMaster();

    const synth: any = new Tone.PolySynth(Tone.Synth, {
      oscillator: {
        type: 'sine',
      }
    }).toMaster();

```

The console had nothing to say. I had to reload the page to stop the sound.

**Comment by tambien** [comment] 2020-05-01 18:35
would it be possible to create an example reproducing this issue? I'm unable to reproduce this issue on my side with that code.

**Comment by stephaneeybert** [comment] 2020-05-01 20:08
Yes, such an example already exist, it is the one linked to above in the thread.

It has the tone@next version.

I [played it](https://stackblitz.com/edit/angular-tone-4hcdqg) on Chrome now and it showcased a failing sound, with some kind of static.

You can try to play it and you should not hear any real playing, but only some static sound.

**Comment by tambien** [comment] 2020-05-01 20:56
your example doesn't make any sound for me no matter which buttons i click on. Looks like you're triggering the attack and decay at the same time. If i update line 81 to this: `this.synth.triggerRelease(placedChord.renderAbc(), triggerTime + 0.1);` then i can hear the notes, but am not getting the distortion you mentioned.

**Comment by stephaneeybert** [comment] 2020-05-01 21:38
My example had some fault. I fixed it. It now plays and shows the behaviour explained in it. It does so even on the next release of Tone 14.6.0 and no garbled sound nor static is heard. I will see if I can replicate in this example the issue I see in my project.

**Comment by tambien** [comment] 2020-05-12 16:47
Seems like the original issue is fixed. If you're able to create a test case for the issue you're having with the PolySynth, please open a new issue for that

**Closed by tambien** 2020-05-12 16:47 UTC
