### ISSUE TITLE
Limiter doesn't seem to be working

### ISSUE THREAD

**Issue by firelex** [Tonejs/Tone.js#770] opened 2020-10-25 12:51 UTC
I noticed that the limiter in tonejs isn't working, which is a problem when I export a track using the Offline() method.  Perhaps this is the reason why Limiter isn't part of the ToneJS documentation page links on the left-hand side.  When you go to the actual example page (https://tonejs.github.io/docs/14.7.39/Limiter) and play with the values passed into the limiter, you can hear a distortion the lower you set the threshold, but the way a limiter should work is to cut off levels above the threshold - this doesn't seem to be the case here.

I'm working around this a bit with the following:

let offlineLimiter = Tone.getContext().destination.chain( new Tone.Compressor( -5, 2.5 ), new Tone.Limiter( -1.5 ), new Tone.Volume( -3 ) );

But what I really do here is I rely on the lowering the master volume to bring the signal in line.  The limiter alone still gives me above zero values on the meter when I listen to the exported audio buffer.  It also makes no difference whether I chain the limiter before the destination or after.

Am I doing something wrong?

Bugs and feature requests only please. For help questions, check out the [forum](https://groups.google.com/forum/#!forum/tonejs).

**Note**: Browsers' [Autoplay Policy](https://github.com/Tonejs/Tone.js/wiki/Autoplay) leads to a lot of subtle and inconsistent bugs where Tone.js produces no sound. Check out the link for more information and the solution. 

Please include a way to reproduce your issue

https://jsfiddle.net/1f60jkq4/ (tone@latest)
https://jsfiddle.net/z9marxbt/ (tone@next)

**Comment by firelex** [comment] 2020-10-25 14:32
Even if this chain:

Tone.getContext().destination.chain( new Tone.Compressor( -5, 3 ), new Tone.Compressor( -2.5, 5 ), new Tone.Compressor( { attack: 0.001, release: 0.001, threshold: -1.5, ratio: 20 } ), new Tone.Compressor( { attack: 0.001, release: 0.001, threshold: -1, ratio: 20 } ), new Tone.Compressor( { attack: 0.001, release: 0.001, threshold: -0.5, ratio: 20 } ), new Tone.Volume( -5 ) );

barely keeps the peak at 0.0.

**Comment by tambien** [comment] 2020-10-25 15:52
Limiter not appearing in the sidebar was just an oversight, it's fixed in the latest version of the docs: https://tonejs.github.io/docs/latest/Limiter.html

Seems like the limiter distortion is caused by the attack/release being set to 0. I think probably the solution is just to set it to a slightly larger value which will remove the distortion. 

Looking at your chain, it seems like you're trying to keep the output values at -5db by chaining a bunch of compressors is that right? 

How are you measuring your output level? If it's with Tone.Meter, then i can see where the issue would be coming in. Tone.Meter and Tone.Compressor don't share the same envelope following code, which means that for example -12db in Tone.Meter is not necessarily the same as setting -12db on the compressor. Tone.Meter uses RMS calculated from the waveform on the draw-frame. The native DynamicsCompressorNode (Tone.Compressor is a thin wrapper around the native DynamicsCompressorNode) uses an internal EnvelopeFollower so the two values are not really interchangeable.

**Comment by firelex** [comment] 2020-10-25 16:35
Thanks, tambien.  Does limiter have attac/release options?  I quote from the latest documentation:

interface LimiterOptions
context : BaseContext
threshold : Decibels
Defined in: Tone/component/dynamics/Limiter.ts

I've measured the clipping of the resulting mix in a DAW.  I just spoke to a producer friend of mine, and he said I should turn down the individual instruments before they go into the master effects.  I'd sampled them closed to zero originally (none of them clipped individually), but maybe the combined effect is just too much for the master effects.  I'd assumed the limiter will not let anything pass above zero, but that doesn't seem to be the case.  @tambien - if you think the limiter SHOULD not let anythign pass above zero, I'm happy to try and set up a JSfiddle that shows the problem.

**Comment by tambien** [comment] 2020-10-25 17:02
it's implemented with a Tone.Compressor with a very fast attack/release and the max compression ratio, so it's the closest thing to a limiter using only native nodes, but is capable of producing values above the threshold.

**Closed** 2020-10-25 17:06 UTC
