### ISSUE TITLE
Tone.Player.state does not properly reflect if playbackRate is increased.

### ISSUE THREAD

**Issue by frigginglorious** [Tonejs/Tone.js#301] opened 2018-02-06 18:08 UTC
I am using Tone.js to play a song. I am using .state to find out when the song was finished playing, which works fine until playbackRate is changed.

Expected Results: Tone.Player.state returns "stopped" whenever the audio is finished playing.

Actual Results: Tone.Player.state will continue to return "started" well after the audio is finished playing, if the audio has an increased playbackRate.

I believe the Tone.state operates the same regardless of playbackRate setting, but I need to test further, and I plan to submit a reproduction.

**Comment by tambien** [comment] 2018-02-07 23:26
Duplicate of #292

**Closed by tambien** 2018-02-07 23:26 UTC
