### ISSUE TITLE
Pending Deprecations

### ISSUE THREAD

**Issue by AnthonyArtmann** [Tonejs/Tone.js#283] opened 2017-12-17 03:03 UTC
[Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

Tone.min.js:7 [Deprecation] OscillatorNode.frequency.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

[Deprecation] OscillatorNode.detune.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.

This library is pure genius!  Thanks!

**Comment by tambien** [comment] 2017-12-17 17:44
Thanks! i'm looking forward to Chrome finally fixing this. Shouldn't affect anything Tone.js-wise.

Duplicate of #282

**Closed by tambien** 2017-12-17 17:44 UTC

**Comment by vibertthio** [comment] 2017-12-28 10:27
@tambien 
Sorry, I don't quite get it.
The warning came from the setting ``node.value = 0``.
https://github.com/Tonejs/Tone.js/blob/d19142a16909a7ec80fd67e65605c136084c1dd3/Tone/signal/SignalBase.js#L41
Therefore, the message is telling you the deprecation of the implement of the Web Audio API (?)
Two question:
1. Is this the reason why you said it shouldn't affect anything in Tone.js?
2. Do we have to use setTargetAtTime() anywhere in Tone.js?

Thanks a lot.

**Comment by tambien** [comment] 2017-12-28 22:14
Basically Chrome had the wrong implementation for setting `AudioParam.value` for the past few years. The change is small and unnoticeable in most situations. Under the hood, Chrome would _secretly_ apply a short setTargetAtTime to smooth the harsh transition that immediately setting an AudioParam value creates. None of the Tone.js synths, effects or scheduling relies on the smoothed transition that Chrome is now removing, which is why i don't think it will change anything for Tone.js. If your application relied on that smoothing that Chrome was applying then this may affect the sound slightly. My recommendation is always to use setValueAtTime instead of directly setting AudioParam.value which will result in more consistent behavior. 

Hope that clarifies things!
