### ISSUE TITLE
Tone.Buffer problems

### ISSUE THREAD

**Issue by phesterman** [Tonejs/Tone.js#177] opened 2016-11-06 13:42 UTC
Hi,

I've recently been experimenting with r8 before incorporating it in my project, and I've run into a problem with Tone.Player and Tone.Sampler where the audio buffer doesn't seem to fill beyond 95% and everything just hangs.  This has occurred with my own code, but also with the examples in the r8 package.  What's interesting is that although grainPlayer.html, for example, exhibits this behavior in the browser on the desktop (both Safari and Chrome in macOS), the example works perfectly in the browser on the iPad.  Anyway, here's some code from the player.html example with Tone.Buffer.on functions added that will illustrate the problem:

`
	<script type="text/javascript">

		// buffer loading progress
		Tone.Buffer.on("progress", function(percentage) {console.log(percentage);});	
		Tone.Buffer.on("load", function() {console.log("complete");});	

		//the player
		var player = new Tone.Player({
			"url" : "./audio/FWDL.mp3",
			"loop" : true,
			"loopStart" : 0.101,
			"loopEnd" : 0.211,
		}).toMaster();
	</script>
`

The progress percentage last logs at .95, "complete" is never logged.  BTW the same thing happens with Tone.Buffers.

Thanks,

Peter

**Comment by tambien** [comment] 2016-11-07 00:01
I'm unable to reproduce. Just tested [this example](https://tonejs.github.io/examples/player.html) which uses `Tone.Buffer.on("load", callback)` on a couple browsers and it worked for me. 

Does that example work for you? Are there any errors on the console when you run your code? 

One update to Tone.Buffer between r7 and r8 is that the XHR loading only brings the progress up to 95% and the remaining 5% is given when decodeAudioData completes. On certain devices decodeAudioData can take a significant amount of time and it seemed weird to stall at 100% for a long time. so instead i made it so that the XHR loading brings the progress to 95% and the last 5% happens when the audio is decoded. 

Is is possible the file type you're using is somehow not able to be decoded? 

The only other thing i can think of between r7 and r8 is the use of Promises, but those [seem to be well supported](http://caniuse.com/#feat=promises). Are you using a browser version which does not support Promises? 

Please provide a minimal test case if possible.

**Comment by phesterman** [comment] 2016-11-07 12:46
Thanks for the quick reply.  The example you included worked correctly, so the problem must be on my end.  I was testing on a Mac using CodeKit (which I recently upgraded) as a server…maybe I screwed something up in some setting there.  I’ll keep experimenting this morning, and I’ll let you know if I continue to have difficulties.

Thanks again!

Peter


On Nov 6, 2016, at 6:01 PM, Yotam Mann <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm unable to reproduce. Just tested this example<https://tonejs.github.io/examples/player.html> which uses Tone.Buffer.on("load", callback) on a couple browsers and it worked for me.

Does that example work for you? Are there any errors on the console when you run your code?

One update to Tone.Buffer between r7 and r8 is that the XHR loading only brings the progress up to 95% and the remaining 5% is given when decodeAudioData completes. On certain devices decodeAudioData can take a significant amount of time and it seemed weird to stall at 100% for a long time. so instead i made it so that the XHR loading brings the progress to 95% and the last 5% happens when the audio is decoded.

Is is possible the file type you're using is somehow not able to be decoded?

The only other thing i can think of between r7 and r8 is the use of Promises, but those seem to be well supported<http://caniuse.com/#feat=promises>. Are you using a browser version which does not support Promises?

Please provide a minimal test case if possible.

**Comment by tambien** [comment] 2016-11-07 15:23
Great. gonna close this for now. Reopen if you find a problem.

**Closed by tambien** 2016-11-07 15:23 UTC
