### ISSUE TITLE
Missing notes after 4 minutes on iOS Safari

### ISSUE THREAD

**Issue by Freeride91** [Tonejs/Tone.js#784] opened 2020-11-11 13:24 UTC
Hey Tambien!

Thank you for developing Tone.js! :) It is a very big help for many of us!!
I am working on my first own project for about three months now, and i'm using your package to it.

I am facing a problem, and i can not fix it for days now: on Mobile iOS, after four minutes, sounds start to randomly dissapear, and glitch. I tried everything i could. Here is a small **CodeSandbox example**: https://codesandbox.io/s/sad-firefly-kswk2

I tested it on iPhone 6 running iOS 12.4.8, and on iPhone 7plus running iOS 14.0.1, both with Safari and Chrome there, and the problem is the same - at 4 minutes 15 seconds, notes start missing randomly.  (On iPad, it works correctly.)

The only solution for me now is to refresh the page. How could i fix this? What could cause this problem?
It is really important for me, because I am building my project https://vocalroutine.com , and i need to play my patterns for longer periods of time. And my users will definitely use the app from iPhones.

I am looking forward to your answer,
Greetings from Hungary
Andrew

**Comment by tambien** [comment] 2020-11-11 14:26
Thanks for the test case. seems to be a duplicate of #742, let's continue tracking the bug there. 

This is a tough one to debug but seems like the clock goes off after some amount of time on Safari, my first guess would be some kind of a floating point rounding issue.

**Closed by tambien** 2020-11-11 14:26 UTC

**Comment by Freeride91** [comment] 2020-11-11 16:58
Thanks for the reply!

I need to correct my description, it produces the same problem on Mac - Safari as well. I just tested it with version 13.1.3. on macOS Catalina.

**Comment by Freeride91** [comment] 2020-12-11 11:18
Hey @tambien! :)

Could you please update me on this issue? :) Could you reproduce this? I don't yet know how it's done here, but is it expected to be fixed in the near future? <3

Best Regards,
Andrew

**Comment by tambien** [comment] 2021-01-13 18:05
@Freeride91 is this still an issue for you? I'm no longer able to produce this error, so might be something that Safari fixed on their side? I'm running Safari 14.0.1. I let it run the codesandbox for about 10 minutes and was still perfectly in sync at the end.
